### ISSUE TITLE
Permission issue (Pure-Perms)

### ISSUE THREAD

**Issue by Nico4898** [Falkirks/BattleKits#10]
When I'm trying to set the perm battlekits.sign.use, then the plugin still keeps saying, that I would'nt
have any perms for this Kit.

**Comment by JoahDave** [comment]
First you must give the player the BattleKits perm. /setuperm <player> BattleKits You can then restrict certain kits or actions by removing a perm.

**Comment by Nico4898** [comment]
I'm using the command /setgperm Player battlekits.sign.use , but it still doesn't work.

**Comment by JoahDave** [comment]
Again, use the command /setgperm Player BattleKits first!

**Comment by Nico4898** [comment]
And then? When I execute the cmd /setgperm Player Battlekits and then /setgperm Player Battlekits.sign.use --> DOES NOT WORK.... :/

**Comment by Nico4898** [comment]
Or could you please explain me whicht perms I have to add in order to make the kit archer only available for the group Player?

**Comment by Nico4898** [comment]
Fixed it on my own. ;)
