### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by AnonymousBay** [Falkirks/BattleKits#12]
any way to add effect to the class ?
or could u add that to the plugin?

**Comment by JoahDave** [comment]
That would be cool!

**Comment by AnonymousBay** [comment]
say ya be good

**Comment by Falkirks** [comment]
You could just use the /effect command.

**Comment by AnonymousBay** [comment]
but i want it for when the player tap the sign it gives them the effect and the items

**Comment by JoahDave** [comment]
Yeah, you could just use the effect command. In the command section of the kit, just put the command "effect {player} (effect) (duration) (amplifier)"

**Comment by AnonymousBay** [comment]
OHHHHHHHHHHHHHHH Thank you :+1: :100:
