### ISSUE TITLE
Permissions. I'm sure you hear that a lot.

### ISSUE THREAD

**Issue by MineplexOfficial** [Falkirks/BattleKits#5]
Love your plugin! Just one thing...
Non op players cannot use kit signs. Can you fix this by adding an option for sign usage by non ops in the config.yml? Please add/fix this!

**Comment by Falkirks** [comment]
`battlekits.sign.use`
Adding an option in the config.yml would add uneeded bloat which would slow the plugin (theoretically). I find this unfair on the users who can setup their permissions correctly.

**Comment by MineplexOfficial** [comment]
Can you recommend a plugin that handles permissions? If so, please include a link to the download page.

**Comment by JoahDave** [comment]
Try PurePerms.
Google "Minecraft PE plugins"
Go to the PocketMine website and search what you need.

**Comment by MineplexOfficial** [comment]
Thanks!
