### ISSUE TITLE
Kit 17 problem

### ISSUE THREAD

**Issue by BattleKitsIsAwesome** [Falkirks/BattleKits#7]
I have a problem when I run out of kits. I can have no more than 17 kit at once or they do not work when they are tapped. Can you add more kits?
(Sorry for bad English It is not my first language)

**Comment by Falkirks** [comment]
There is no limit on the amount of kits your can have. Are you sure you haven't made a formatting mistake in your yml file?

**Comment by BattleKitsIsAwesome** [comment]
Does the whole plugin stop working if you mistake in the yml file?

**Comment by Falkirks** [comment]
Things will get misinterpreted. Everything could stop working or it could just ignore messed up entries. It depends on the error.

**Comment by BattleKitsIsAwesome** [comment]
Thank you for help. I see if my problem is fixed gone!
