### ISSUE TITLE
I can't have more than 17 kits!

### ISSUE THREAD

**Issue by JoahDave** [Falkirks/BattleKits#8]
I saw a post that said you couldn't have more than 17 kits at once. I tried this myself and got the same result. I noticed that having more than 17 kits only affected the kit signs, not the usage of the /battlekits command. 
Please take a look at this!

**Comment by JoahDave** [comment]
I'm pretty sure there is no formatting mistake in the configuration file.

**Comment by Falkirks** [comment]
Why 17 though?

**Comment by JoahDave** [comment]
How can I know?

Did you try this many kits and get the same result?

**Comment by Falkirks** [comment]
No I haven't yet abacus I don't understand what happens when you have 17 kits. Can you not create kit signs? Can you not use them?

**Comment by JoahDave** [comment]
You can't use kit signs in any way.

**Comment by JoahDave** [comment]
Have you taken a look at this?

**Comment by JoahDave** [comment]
Now this is embarrassing...
Turns out my version of PocketMine was not up to date! Wooooooow.
It works fine on the version I upgraded to. Wooooooooooow.

Well, sorry to disturb you! There is nothing wrong with your plugin! 

Thanks for following!

**Comment by PEMapModder** [comment]
Though, strange that it is 17 (reminds me of `0x11`) and how it's affected by the PocketMine version.

**Comment by JoahDave** [comment]
What changed in-between the versions?
That's what I wonder
